### ISSUE TITLE
when you set your NODE_PATH / NODE_ENV can i just export those variables to at least get this thing running..... i feel lik im super close

### ISSUE THREAD

**Issue by zarboz** [kmalinich/node-bmw-helpers#1]
https://github.com/kmalinich/node-bmw-helpers/blob/3b94ea4ec54013832367f371b9063eb1ae50f995/systemd/bmwi%40.service#L14

unless you wanna dump your sdcard LOL 
 im super close to getting this running I feel like any input would be welcomed

**Comment by kmalinich** [comment]
Yeah, just sub in the path you're using if it's not /use/local/bmwi. The node-bmw bash script should give you an example of how that works

**Comment by zarboz** [comment]
OK I think this might close my other issue once I figure out how to get the ENV tag to work properly as the import errors are seemingly related to the .js files in lib and modules folder you already wrote that need importing

**Comment by zarboz** [comment]
got it running now to figure out how to wire this up to the car LOL
